# ------------------------------------------------------------
# ansible/playbook/roles/package_redis_client_setup/tasks/main.yml

---

# ------------------------------------------------------------
# Super user block
- name: Setup redis client by super user
  become: true
  become_user: "{{ become_super_user }}"
  # ignore_errors: true
  block:

    # ------------------------------------------------------------
    # RedHat 9 type on super user block
    - name: Setup redis client on redhat9 by super user
      when: ansible_distribution_file_variety == "RedHat"
        and ansible_distribution_major_version == "9"
      # ignore_errors: true
      block:

        # ------------------------------------------------------------
        - name: Install redis client
          ansible.builtin.dnf:
            name: "{{ item }}"
            # state: latest
            state: present
          with_items:
            - redis

# ------------------------------------------------------------
# EOF
