# ------------------------------------------------------------
# ansible/playbook/playbook_package_mariadb_setup.yml

---

# ------------------------------------------------------------
- name: Setup mariadb server
  hosts: mariadb
  tags: mariadb,mariadb_server
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/vars/common_vars.yml"
  roles:
    - role: package_mariadb_server_setup
      when: setup_rdb is defined
        and setup_rdb
        and setup_mariadb_server is defined
        and setup_mariadb_server
        and is_rdb_server is defined
        and is_rdb_server
        and is_mariadb is defined
        and is_mariadb

# ------------------------------------------------------------
- name: Setup mariadb client
  hosts: all
  tags: mariadb,mariadb_client
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/vars/common_vars.yml"
  roles:
    - role: package_mariadb_client_setup
      when: setup_rdb is defined
        and setup_rdb
        and setup_mariadb_client is defined
        and setup_mariadb_client
        and is_rdb_client is defined
        and is_rdb_client

# ------------------------------------------------------------
# EOF
